import {
  ArrowDown,
  ArrowRight,
  BarChart3,
  Building2,
  ClipboardCheck,
  FileText,
  Link2,
  ShieldCheck,
  Store,
  Ticket,
  Users,
  Wallet,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Link } from "react-router-dom";
import platformLogo from "../../logo.jpg";

type AccentKey = "violet" | "blue" | "indigo" | "emerald" | "amber" | "orange";

const accents: Record<AccentKey, { border: string; glow: string; color: string }> = {
  violet: { border: "rgba(192,132,252,0.40)", glow: "rgba(168,85,247,0.24)", color: "#C084FC" },
  blue: { border: "rgba(96,165,250,0.42)", glow: "rgba(59,130,246,0.24)", color: "#60A5FA" },
  indigo: { border: "rgba(129,140,248,0.40)", glow: "rgba(99,102,241,0.24)", color: "#818CF8" },
  emerald: { border: "rgba(52,211,153,0.36)", glow: "rgba(16,185,129,0.20)", color: "#34D399" },
  amber: { border: "rgba(251,191,36,0.36)", glow: "rgba(245,158,11,0.20)", color: "#FBBF24" },
  orange: { border: "rgba(251,146,60,0.36)", glow: "rgba(249,115,22,0.20)", color: "#FB923C" },
};

const shellBackground =
  "radial-gradient(circle at 12% 8%, rgba(59,130,246,0.24), transparent 28%), " +
  "radial-gradient(circle at 46% 6%, rgba(168,85,247,0.22), transparent 24%), " +
  "radial-gradient(circle at 88% 28%, rgba(99,102,241,0.20), transparent 26%), " +
  "radial-gradient(circle at 82% 86%, rgba(14,165,233,0.16), transparent 28%), " +
  "linear-gradient(180deg, #081426 0%, #06101F 42%, #020611 100%)";

const sectionPanelBase: React.CSSProperties = {
  background: "linear-gradient(180deg, rgba(13,24,43,0.96) 0%, rgba(7,14,28,0.94) 100%)",
  border: "1px solid rgba(148,163,184,0.16)",
  boxShadow: "0 28px 80px rgba(0,0,0,0.40), inset 0 1px 0 rgba(255,255,255,0.06)",
  borderRadius: 34,
};

const glassCardBase: React.CSSProperties = {
  background: "linear-gradient(180deg, rgba(15,27,48,0.94) 0%, rgba(8,16,32,0.92) 100%)",
  border: "1px solid rgba(255,255,255,0.10)",
  boxShadow: "0 18px 48px rgba(0,0,0,0.30), inset 0 1px 0 rgba(255,255,255,0.05)",
};

const routeStations = [
  { number: "01", title: "Допуск", subitems: ["Организатор", "Заявка", "Регулятор"], icon: ShieldCheck, accent: "violet" as const },
  { number: "02", title: "Регистрация", subitems: ["Реестр", "Мероприятие", "Билеты"], icon: FileText, accent: "blue" as const },
  { number: "03", title: "Продажа", subitems: ["Каналы продаж", "Покупатель"], icon: Store, accent: "emerald" as const },
  { number: "04", title: "Контроль и данные", subitems: ["Контроль", "Аналитика"], icon: BarChart3, accent: "indigo" as const },
];

const problemCards = [
  { title: "Разрозненные продажи", text: "Отдельные реселлеры, квоты и ручные договоренности.", icon: Store, accent: "orange" as const },
  { title: "Неполная прозрачность", text: "Государство видит рынок фрагментарно.", icon: ShieldCheck, accent: "blue" as const },
  { title: "Зависимость организатора", text: "Организатор привязан к отдельным продавцам и каналам.", icon: Building2, accent: "violet" as const },
  { title: "Потерянная ликвидность", text: "Реселлер продает не весь рынок, а ограниченные квоты.", icon: Ticket, accent: "amber" as const },
];

const circuitDomains = [
  { title: "Организаторский контур", nodes: ["Организатор", "Заявка", "Документы"], icon: Building2, accent: "violet" as const },
  { title: "Регуляторный контур", nodes: ["Рассмотрение", "Решение", "Реестр"], icon: ShieldCheck, accent: "blue" as const },
  { title: "Коммерческий контур", nodes: ["Билеты", "Каналы продаж", "Покупатель"], icon: Ticket, accent: "emerald" as const },
  { title: "Контур данных", nodes: ["Продажи", "Возвраты", "Контроль", "Аналитика"], icon: BarChart3, accent: "indigo" as const },
];

const journeySteps = [
  { number: "01", title: "Подача заявки", caption: "Организатор подает заявку на мероприятие.", icon: ClipboardCheck, accent: "violet" as const },
  { number: "02", title: "Рассмотрение", caption: "Регулятор проверяет и согласовывает.", icon: FileText, accent: "blue" as const },
  { number: "03", title: "Включение в реестр", caption: "Мероприятие получает официальный статус.", icon: ShieldCheck, accent: "indigo" as const },
  { number: "04", title: "Выпуск билетов", caption: "Билетный фонд создается в цифровой среде.", icon: Ticket, accent: "emerald" as const },
  { number: "05", title: "Подключение каналов", caption: "Реселлеры получают доступ к продаже.", icon: Link2, accent: "blue" as const },
  { number: "06", title: "Продажа покупателю", caption: "Покупатель приобретает цифровой билет.", icon: Store, accent: "violet" as const },
  { number: "07", title: "Контроль и аналитика", caption: "Система фиксирует операции и данные.", icon: BarChart3, accent: "indigo" as const },
];

const benefitCards = [
  { title: "Государство / Минкульт", text: "Прозрачность рынка, контроль в реальном времени и достоверные данные для решений.", icon: ShieldCheck, accent: "blue" as const },
  { title: "Организатор", text: "Быстрый легальный маршрут: заявка, согласование, выпуск билетов и продажи.", icon: Building2, accent: "violet" as const },
  { title: "Реселлер", text: "Больше доступных мероприятий и защищенный стандарт подключения к билетному фонду.", icon: Store, accent: "emerald" as const },
  { title: "Покупатель", text: "Понятный цифровой билет, безопасная покупка, возврат и проверка.", icon: Users, accent: "amber" as const },
];

const architectureCards = [
  { number: "01", title: "Кабинет организатора", description: "Регистрация, заявки, документы, мероприятия, статусы, история взаимодействия.", icon: Building2, accent: "violet" as const },
  { number: "02", title: "Регуляторный контур", description: "Рассмотрение заявок, реестры, решения, журнал действий, контроль и аналитика.", icon: ShieldCheck, accent: "blue" as const },
  { number: "03", title: "Каналы продаж", description: "Подключение реселлеров, API/виджет, продажи, возвраты, проверки, синхронизация билетного фонда.", icon: Ticket, accent: "emerald" as const },
  { number: "04", title: "Публичный контур", description: "Афиша, покупка билета, цифровой билет, возврат и проверка на входе.", icon: Users, accent: "orange" as const },
];

function AccentIcon({ icon, accent, size = 18 }: { icon: LucideIcon; accent: AccentKey; size?: number }) { const Icon = icon; return <div className="flex h-11 w-11 items-center justify-center rounded-[14px] border" style={{ borderColor: accents[accent].border, color: accents[accent].color, background: accents[accent].glow }}><Icon size={size} /></div>; }
const SectionPanel = ({ children, className = "", style }: { children: React.ReactNode; className?: string; style?: React.CSSProperties }) => <section className={`rounded-[34px] px-5 py-6 md:px-7 md:py-8 ${className}`} style={{ ...sectionPanelBase, ...style }}>{children}</section>;
const GlassCard = ({ children, className = "", accent }: { children: React.ReactNode; className?: string; accent?: AccentKey }) => <article className={`relative overflow-hidden rounded-[24px] border p-4 ${className}`} style={{ ...glassCardBase, borderColor: accent ? accents[accent].border : "rgba(255,255,255,0.10)" }}>{accent && <div className="pointer-events-none absolute -right-8 -top-8 h-24 w-24 rounded-full blur-2xl" style={{ background: accents[accent].glow }} />}<div className="relative">{children}</div></article>;
function ArrowBadge({ direction }: { direction: "right" | "down" }) { const Icon = direction === "right" ? ArrowRight : ArrowDown; return <div className="flex h-11 w-11 items-center justify-center rounded-full border" style={{ borderColor: "rgba(191,219,254,0.22)", background: "rgba(15,23,42,0.76)", boxShadow: "0 0 32px rgba(96,165,250,0.26)", color: "#DBEAFE" }}><Icon size={18} /></div>; }

function RouteStation({ station }: { station: (typeof routeStations)[number] }) { const Icon = station.icon; return <GlassCard accent={station.accent} className="rounded-[26px] p-5 md:min-h-[184px]" ><div className="flex items-center justify-between"><span className="rounded-full border px-3 py-1.5 text-[11px] font-semibold tracking-[0.16em]" style={{ borderColor: accents[station.accent].border, background: "rgba(255,255,255,0.04)", color: accents[station.accent].color }}>{station.number}</span><AccentIcon icon={Icon} accent={station.accent} /></div><h3 className="mt-4 text-[20px] font-semibold">{station.title}</h3><div className="mt-4 flex flex-wrap gap-2">{station.subitems.map((s) => <span key={s} className="rounded-full border px-2.5 py-1 text-[11px]" style={{ background: "rgba(255,255,255,0.06)", borderColor: "rgba(191,219,254,0.20)", color: "rgba(219,234,254,0.92)" }}>{s}</span>)}</div></GlassCard>; }

function EventRouteDiagram() { return <div className="rounded-[30px] p-5 md:p-6" style={{ ...glassCardBase, border: "1px solid rgba(96,165,250,0.28)", background: "radial-gradient(circle at 20% 0%, rgba(168,85,247,0.16), transparent 32%), radial-gradient(circle at 90% 100%, rgba(59,130,246,0.14), transparent 34%), linear-gradient(180deg, rgba(15,27,48,0.94) 0%, rgba(8,16,32,0.92) 100%)" }}><div className="flex items-start justify-between gap-4"><div><h3 className="text-[28px] md:text-[36px] font-semibold tracking-[-0.04em]">Маршрут события</h3><p className="mt-2 text-[13px] leading-5 text-[rgba(203,213,225,0.68)]">От допуска организатора до контроля продаж</p></div><span className="rounded-full border px-3 py-1 text-[11px] uppercase tracking-[0.14em]" style={{ borderColor: "rgba(96,165,250,0.26)", background: "rgba(59,130,246,0.10)", color: "rgba(191,219,254,0.9)" }}>Lifecycle map</span></div><div className="mt-6 hidden md:grid md:grid-cols-[1fr_auto_1fr] md:items-center md:gap-3"><RouteStation station={routeStations[0]} /><ArrowBadge direction="right" /><RouteStation station={routeStations[1]} /><ArrowBadge direction="down" /><div /><div /><RouteStation station={routeStations[2]} /><ArrowBadge direction="right" /><RouteStation station={routeStations[3]} /></div><div className="mt-6 grid justify-items-start gap-3 md:hidden"><RouteStation station={routeStations[0]} /><ArrowBadge direction="down" /><RouteStation station={routeStations[1]} /><ArrowBadge direction="down" /><RouteStation station={routeStations[2]} /><ArrowBadge direction="down" /><RouteStation station={routeStations[3]} /></div></div>; }

function DomainCard({ domain }: { domain: (typeof circuitDomains)[number] }) { return <GlassCard accent={domain.accent} className="rounded-[26px] p-5"><div className="flex items-center justify-between"><span className="text-[11px] uppercase tracking-[0.14em] text-[rgba(191,219,254,0.85)]">контур</span><AccentIcon icon={domain.icon} accent={domain.accent} /></div><h4 className="mt-4 text-[20px] font-semibold">{domain.title}</h4><div className="mt-3 flex flex-wrap gap-2">{domain.nodes.map((n) => <span key={n} className="rounded-full border px-2.5 py-1 text-[11px]" style={{ background: "rgba(255,255,255,0.06)", borderColor: "rgba(191,219,254,0.20)", color: "rgba(219,234,254,0.92)" }}>{n}</span>)}</div></GlassCard>; }
function CentralHub() { return <div className="mx-auto flex h-[148px] w-[148px] flex-col items-center justify-center rounded-full text-center md:h-[172px] md:w-[172px]" style={{ background: "radial-gradient(circle at 50% 35%, rgba(96,165,250,0.40), rgba(99,102,241,0.22) 48%, rgba(15,23,42,0.96) 100%)", border: "1px solid rgba(191,219,254,0.34)", boxShadow: "0 0 84px rgba(96,165,250,0.28), inset 0 1px 0 rgba(255,255,255,0.10)" }}><p className="text-[10px] uppercase tracking-[0.18em] text-[rgba(191,219,254,0.82)]">core</p><p className="mt-1 text-[22px] font-semibold">Событие</p><p className="text-[13px] leading-5 text-[rgba(203,213,225,0.68)]">цифровой объект</p></div>; }
function DigitalCircuitDiagram() { return <div className="relative mt-6 overflow-hidden rounded-[30px] p-5 md:p-7" style={{ background: "linear-gradient(180deg, rgba(15,27,48,0.92), rgba(8,16,32,0.90))", border: "1px solid rgba(96,165,250,0.20)", boxShadow: "0 22px 60px rgba(0,0,0,0.32), inset 0 1px 0 rgba(255,255,255,0.06)" }}><div className="pointer-events-none absolute -left-14 -top-16 h-44 w-44 rounded-full blur-3xl" style={{ background: "rgba(168,85,247,0.18)" }} /><div className="pointer-events-none absolute -bottom-16 -right-14 h-44 w-44 rounded-full blur-3xl" style={{ background: "rgba(59,130,246,0.18)" }} /><div className="relative hidden lg:grid lg:grid-cols-[1fr_auto_1fr] lg:items-center lg:gap-4"><DomainCard domain={circuitDomains[0]} /><ArrowBadge direction="right" /><DomainCard domain={circuitDomains[1]} /><ArrowBadge direction="down" /><CentralHub /><ArrowBadge direction="down" /><DomainCard domain={circuitDomains[2]} /><ArrowBadge direction="right" /><DomainCard domain={circuitDomains[3]} /></div><div className="relative grid gap-3 lg:hidden"><CentralHub /><ArrowBadge direction="down" /><DomainCard domain={circuitDomains[0]} /><ArrowBadge direction="down" /><DomainCard domain={circuitDomains[1]} /><ArrowBadge direction="down" /><DomainCard domain={circuitDomains[2]} /><ArrowBadge direction="down" /><DomainCard domain={circuitDomains[3]} /></div></div>; }

function JourneyStep({ step, vertical = false }: { step: (typeof journeySteps)[number]; vertical?: boolean }) { return <div className={vertical ? "relative pl-14" : ""}><div className={vertical ? "absolute left-0 top-0" : "mx-auto w-fit"}><div className="flex h-11 w-11 items-center justify-center rounded-full border text-[12px] font-semibold" style={{ borderColor: accents[step.accent].border, background: "rgba(255,255,255,0.05)", boxShadow: `0 0 24px ${accents[step.accent].glow}` }}>{step.number}</div></div><GlassCard className={vertical ? "min-h-[132px] rounded-[22px] p-4" : "mt-3 min-h-[172px] rounded-[22px] p-4"} accent={step.accent}><AccentIcon icon={step.icon} accent={step.accent} size={16} /><h4 className="mt-3 text-[16px] font-semibold leading-5">{step.title}</h4><p className="mt-2 text-[13px] leading-5 text-[rgba(203,213,225,0.72)]">{step.caption}</p></GlassCard></div>; }
function JourneyRibbon() { return <><div className="mt-6 hidden rounded-[30px] p-5 xl:block" style={glassCardBase}><div className="relative"><div className="absolute left-[56px] right-[56px] top-[58px] h-[2px]" style={{ background: "linear-gradient(90deg, rgba(168,85,247,0.48), rgba(59,130,246,0.58), rgba(16,185,129,0.46), rgba(99,102,241,0.50))" }} /><div className="relative grid grid-cols-7 gap-3">{journeySteps.map((step) => <JourneyStep key={step.number} step={step} />)}</div></div></div><div className="relative mt-6 grid gap-4 xl:hidden"><div className="pointer-events-none absolute bottom-4 left-[22px] top-4 w-[2px]" style={{ background: "linear-gradient(180deg, rgba(168,85,247,0.50), rgba(59,130,246,0.58), rgba(16,185,129,0.48))" }} />{journeySteps.map((step) => <JourneyStep key={step.number} step={step} vertical />)}</div></>; }

export default function MainPage() { return <div className="min-h-screen bg-[#020611] text-white"><div className="pointer-events-none fixed inset-0" style={{ background: shellBackground }} /><div className="relative mx-auto max-w-[1440px] overflow-x-hidden px-4 pb-10 pt-4 md:px-6 xl:px-8"><header className="rounded-[26px] px-5 py-4 md:px-7" style={{ background: "linear-gradient(180deg, rgba(7,13,24,0.92), rgba(5,10,20,0.9))", border: "1px solid rgba(255,255,255,0.07)", boxShadow: "0 16px 44px rgba(0,0,0,0.26)", backdropFilter: "blur(18px)" }}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><img src={platformLogo} alt="CinemaLab" className="h-8 w-8 rounded-lg object-cover" /><span className="text-[17px] font-semibold tracking-[-0.03em]">CinemaLab</span><span className="text-[14px] text-[rgba(203,213,225,0.72)]">Билетная платформа</span></div><Link to="/proto" className="inline-flex items-center gap-2 rounded-[12px] px-4 py-2 text-[13px] font-semibold" style={{ background: "linear-gradient(90deg, #4F7BFF 0%, #B059FF 100%)", boxShadow: "0 14px 32px rgba(99,102,241,0.32)" }}>К прототипу<ArrowRight size={16} /></Link></div></header>
<section className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-[1.08fr_0.92fr]"><SectionPanel className="relative overflow-hidden rounded-[34px] px-6 py-8 md:px-8 md:py-10"><h1 className="text-[38px] md:text-[58px] xl:text-[64px] font-semibold leading-[1.02] tracking-[-0.055em]">Единая цифровая инфраструктура для рынка<span className="block" style={{ background: "linear-gradient(90deg, #E9D5FF 0%, #C084FC 36%, #60A5FA 100%)", WebkitBackgroundClip: "text", color: "transparent" }}>культурно-массовых мероприятий</span></h1><p className="mt-5 text-[16px] leading-8 text-[rgba(213,223,246,0.82)]">Платформа связывает организаторов, регулятора, площадки, реселлеров и покупателей в единый управляемый контур: от допуска организатора и согласования мероприятия до продажи билета, контроля и аналитики.</p><p className="mt-4 text-[16px] leading-8 text-[rgba(233,238,255,0.9)]">Это не еще одна афиша. Это цифровой слой, который соединяет регулирование, билетную продажу и рыночную статистику.</p><div className="mt-6 flex flex-wrap gap-3">{["Регуляторный контур", "Билетная продажа", "Аналитика рынка"].map((chip) => <span key={chip} className="rounded-full border px-4 py-2 text-[13px] leading-5" style={{ borderColor: "rgba(255,255,255,0.12)", background: "rgba(255,255,255,0.04)" }}>{chip}</span>)}</div></SectionPanel><EventRouteDiagram /></section>
<SectionPanel className="mt-5"><h2 className="text-[28px] md:text-[36px] font-semibold tracking-[-0.04em]">Рынок сломан, но уже регулируется</h2><p className="mt-3 text-[16px] leading-8 text-[rgba(213,223,246,0.82)]">Рынок уже находится в обязательном регуляторном контуре, но коммерческая инфраструктура остается фрагментированной: продажи, квоты, договоренности и аналитика живут отдельно друг от друга.</p><div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">{problemCards.map((card) => <GlassCard key={card.title} accent={card.accent} className="p-5"><div className="flex items-center gap-3"><AccentIcon icon={card.icon} accent={card.accent} /><span className="text-[13px] leading-5 text-[rgba(203,213,225,0.68)]">Проблема</span></div><h3 className="mt-3 text-[21px] font-semibold">{card.title}</h3><p className="mt-2 text-[14px] leading-6 text-[rgba(213,223,246,0.82)]">{card.text}</p></GlassCard>)}</div></SectionPanel>
<SectionPanel className="mt-5"><h2 className="text-[28px] md:text-[36px] font-semibold tracking-[-0.04em]">Решение: единый цифровой контур</h2><p className="mt-3 text-[16px] leading-8 text-[rgba(213,223,246,0.82)]">Платформа превращает мероприятие в управляемый цифровой объект и соединяет административное согласование с продажами, контролем и аналитикой.</p><DigitalCircuitDiagram /></SectionPanel>
<SectionPanel className="mt-5"><h2 className="text-[28px] md:text-[36px] font-semibold tracking-[-0.04em]">От разрешения до денег — в одном маршруте</h2><JourneyRibbon /></SectionPanel>
<SectionPanel className="mt-5"><h2 className="text-[28px] md:text-[36px] font-semibold tracking-[-0.04em]">Выгоды для каждого участника</h2><p className="mt-3 text-[16px] leading-8 text-[rgba(213,223,246,0.82)]">Платформа работает, когда каждый участник получает практическую выгоду.</p><div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">{benefitCards.map((item) => <GlassCard key={item.title} accent={item.accent} className="rounded-[24px] p-5"><AccentIcon icon={item.icon} accent={item.accent} /><h3 className="mt-3 text-[22px] font-semibold">{item.title}</h3><p className="mt-2 text-[14px] leading-6 text-[rgba(213,223,246,0.82)]">{item.text}</p></GlassCard>)}</div></SectionPanel>
<SectionPanel className="mt-5"><h2 className="text-[28px] font-semibold">Один рынок — четыре рабочих контура</h2><p className="mt-2 text-[15px] leading-7 text-[rgba(203,213,225,0.82)]">Четыре рабочих контура собираются в единую инфраструктуру рынка.</p><div className="mt-6 grid grid-cols-1 gap-4 xl:grid-cols-4">{architectureCards.map((card) => <GlassCard key={card.title} accent={card.accent} className="rounded-[26px] p-5"><div className="flex items-center justify-between"><span className="rounded-full border px-3 py-1.5 text-[11px] font-semibold tracking-[0.16em]" style={{ borderColor: accents[card.accent].border, background: "rgba(255,255,255,0.04)", color: accents[card.accent].color }}>{card.number}</span><AccentIcon icon={card.icon} accent={card.accent} /></div><h3 className="mt-4 text-[20px] font-semibold">{card.title}</h3><p className="mt-2 text-[14px] leading-6 text-[rgba(203,213,225,0.82)]">{card.description}</p><div className="mt-4 h-[2px] rounded-full" style={{ background: accents[card.accent].glow }} /></GlassCard>)}</div><p className="mt-5 rounded-[24px] border px-5 py-4 text-[16px] leading-7" style={{ background: "rgba(59,130,246,0.08)", borderColor: "rgba(96,165,250,0.18)" }}>Прототип демонстрирует не отдельную страницу и не кабинет ради кабинета. Он показывает модель будущей инфраструктуры: как мероприятие проходит путь от организатора и регулятора до продажи билета и отражения операции в системе.</p></SectionPanel>
<SectionPanel className="mt-5"><h2 className="text-[28px] font-semibold">Деньги уже есть в рынке</h2><p className="mt-4 leading-8 text-[rgba(203,213,225,0.82)]">Сегодня организатор передает билеты реселлеру. Реселлер продает билет покупателю и удерживает комиссию.</p><div className="mt-6 grid grid-cols-1 gap-4 xl:grid-cols-[1fr_auto_1fr_auto_1fr] xl:items-center"><GlassCard accent="blue" className="p-5 text-center"><p className="text-[14px] text-[rgba(203,213,225,0.78)]">Номинал билета</p><p className="mt-2 text-[34px] font-semibold md:text-[40px]">100 BYN</p></GlassCard><div className="mx-auto"><ArrowBadge direction="right" /></div><GlassCard accent="emerald" className="p-5 text-center"><p className="text-[14px] text-[rgba(203,213,225,0.78)]">Организатору</p><p className="mt-2 text-[34px] font-semibold md:text-[40px]">90 BYN</p><p className="mt-1 text-[13px] text-[rgba(203,213,225,0.72)]">возврат после комиссии</p></GlassCard><div className="mx-auto"><ArrowBadge direction="right" /></div><GlassCard accent="amber" className="p-5 text-center"><p className="text-[14px] text-[rgba(203,213,225,0.78)]">Комиссионный слой</p><p className="mt-2 text-[34px] font-semibold md:text-[40px]">10 BYN</p><p className="mt-1 text-[13px] text-[rgba(203,213,225,0.72)]">зона монетизации платформы</p></GlassCard></div><p className="mt-3 leading-8 text-[rgba(203,213,225,0.82)]">Именно эта комиссия — существующий денежный слой рынка.</p><div className="mt-5 rounded-[28px] border p-6 text-center text-[20px] font-semibold leading-9" style={{ background: "linear-gradient(90deg, rgba(79,123,255,0.18), rgba(168,85,247,0.14))", borderColor: "rgba(125,106,255,0.30)" }}>Доход платформы = GMV × средняя комиссия продаж × доля платформы</div><div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-3"><div className="rounded-full border px-4 py-2 text-[13px]" style={{ borderColor: "rgba(96,165,250,0.24)", background: "rgba(59,130,246,0.08)" }}>GMV — общий объем проданных билетов.</div><div className="rounded-full border px-4 py-2 text-[13px]" style={{ borderColor: "rgba(96,165,250,0.24)", background: "rgba(59,130,246,0.08)" }}>Средняя комиссия продаж — комиссия, которую рынок уже платит реселлерам.</div><div className="rounded-full border px-4 py-2 text-[13px]" style={{ borderColor: "rgba(96,165,250,0.24)", background: "rgba(59,130,246,0.08)" }}>Доля платформы — часть комиссии за инфраструктуру, доступ, контроль и обработку операций.</div></div></SectionPanel>
<SectionPanel className="mt-5" style={{ border: "1px solid rgba(79,123,255,0.28)", boxShadow: "0 32px 88px rgba(0,0,0,0.42), 0 0 0 1px rgba(125,106,255,0.14)" }}><div className="rounded-[20px] border px-4 py-3" style={{ borderColor: "rgba(125,106,255,0.2)", background: "rgba(79,123,255,0.08)" }}><p className="text-[11px] uppercase tracking-[0.16em] text-[rgba(191,219,254,0.88)]">Financial upside</p><h2 className="mt-1 text-[30px] font-semibold">Потенциал монетизации</h2></div><div className="mt-5 grid grid-cols-1 gap-4 xl:grid-cols-3">{[{ l: "Мероприятий в год", v: "..." }, { l: "Проданных билетов в год", v: "..." }, { l: "Расчетный GMV рынка", v: "... BYN" }, { l: "Средняя комиссия продаж", v: "8–10%" }, { l: "Потенциальная доля платформы в комиссии", v: "...%" }, { l: "Оценочная выручка платформы", v: "... BYN / год" }].map((m) => <GlassCard key={m.l} className="p-5"><p className="text-[14px] leading-6 text-[rgba(203,213,225,0.78)]">{m.l}</p><p className="mt-2 text-[24px] font-semibold">{m.v}</p><div className="mt-3 h-[2px] rounded-full" style={{ background: "linear-gradient(90deg, rgba(96,165,250,0.42), rgba(168,85,247,0.42))" }} /></GlassCard>)}</div><p className="mt-5 leading-8 text-[rgba(233,238,255,0.9)]">Даже небольшая доля в существующей комиссии может формировать значимую выручку, если платформа становится обязательным цифровым маршрутом для рынка мероприятий.</p></SectionPanel>
<footer className="mt-5 rounded-[24px] px-5 py-5" style={sectionPanelBase}><div className="flex items-start gap-3"><AccentIcon icon={Wallet} accent="violet" /><div><p className="leading-8 text-[rgba(233,238,255,0.9)]">Платформа соединяет обязательный регуляторный процесс с реальным коммерческим оборотом рынка.</p><p className="mt-2 leading-8 text-[rgba(233,238,255,0.9)]">Кто контролирует цифровой маршрут мероприятия — тот контролирует данные, доступ к рынку и часть комиссионного потока.</p></div></div></footer></div></div>; }
